services:
  execution:
    build:
      context: .
      dockerfile: ${CLIENT}/Dockerfile
    ports:
      - "8545:8545"       # RPC
      - "8546:8546"       # Websocket
      - "7301:6060"       # Metrics
      - "30303:30303"     # P2P TCP
      - "30303:30303/udp" # P2P UDP
      #command: [ "bash", "./execution-entrypoint", "--authrpc.jwtsecret=/data/jwt.secret",   "--http", "--http.api=web3,eth,net,engine"]
    command: [ "bash", "./execution-entrypoint",
           "--authrpc.jwtsecret=/data/jwt.secret",
           "--http",
           "--http.addr=0.0.0.0",
           "--http.port=8545",
           "--http.api=web3,eth,net,engine,web3,admin,debug,txpool",
           "--http.corsdomain=*",
           "--http.vhosts=*",
           "--ws",
           "--ws.addr=0.0.0.0",
           "--ws.port=8546",
           "--ws.api=debug,eth,net,txpool"
         ]

    volumes:
      - type: bind
        source: ${HOST_DATA_DIR}/jwt.secret
        target: /data/jwt.secret
        read_only: false
    env_file:
      - .env.sepolia
    environment:
      RPC_PORT: "8545"      # ✅ Explicitly define the RPC port
      WS_PORT: "8546"       # ✅ Explicitly define the WebSocket port
      AUTHRPC_PORT: "8551"  # ✅ Explicitly define the Auth RPC port
      METRICS_PORT: "6060"  # ✅ Explicitly define the Metrics port
      RETH_CHAIN: "base-sepolia" # ✅ Define the chain
      JWT_SECRET_PATH: /data/jwt.secret

  node:
    build:
      context: .
      dockerfile: ${CLIENT}/Dockerfile
    depends_on:
      - execution
    ports:
      - "7545:8545"     # RPC
      - "9222:9222"     # P2P TCP
      - "9222:9222/udp" # P2P UDP
      - "7300:7300"     # Metrics
      - "6060:6060"     # pprof
      #command: [ "bash", "./op-node-entrypoint", "--jwt-secret=/data/jwt.secret"]
    command: [ "bash", "./op-node-entrypoint", "--jwt-secret=/data/jwt.secret", "--rpc-enable", "--rpc-enable.admin", "--execution.jwt-secret=/data/jwt.secret"]
      #command: >
      #bash -c './op-node-entrypoint
      #--l1-eth-rpc="${OP_NODE_L1_ETH_RPC}"
      #--l1-beacon="${OP_NODE_L1_BEACON}"
      #--jwt-secret=/data/jwt.secret
      #--rpc.enable
      #--rpc.addr=0.0.0.0
      #--rpc.port=8545
      #--rollup.config=/data/rollup.json'
      #command:
      #- "bash"
      #- "./op-node-entrypoint"
      #- "--l1-eth-rpc=${OP_NODE_L1_ETH_RPC}"  # Connect to Chainstack's L1 Execution Client
      #- "--l1-beacon=${OP_NODE_L1_BEACON}"    # Connect to Chainstack's L1 Beacon Node
      #- "--jwt-secret=/data/jwt.secret"       # Authentication
      #- "--rpc.enable"                        # Enable RPC
      #- "--rpc.addr=0.0.0.0"                   # Listen on all interfaces
      #- "--rpc.port=8545"                      # Expose RPC on port 8545
      #- "--rollup.config=/data/rollup.json"    # Ensure Base Sepolia rollup config
    env_file:
      - .env.sepolia
    volumes:
      - type: bind
        source: ${HOST_DATA_DIR}/jwt.secret
        target: /data/jwt.secret
        read_only: false
        #environment:
        #JWT_SECRET_PATH: /data/jwt.secret
